[io] Fix compilation error with numeric types
Error log:
XXX/Radium-Engine/Radium-Engine/src/Radium-Engine/src/IO/VolumesLoader/VolumeLoader.cpp:183:73:   required from here
XXX/Radium-Engine/Radium-Engine/external/install/include/eigen3/Eigen/src/Geometry/Transform.h:308:5: error: static assertion failed: YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY

https://github.com/STORM-IRIT/Radium-Engine/runs/4844992814?check_suite_focus=true#step:15:3986